//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellenceTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExcellenceTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;&lt;learningPath&gt;&lt;trainingPlanItem&gt;&lt;status&gt;&lt;code&gt;needsAction&lt;/code&gt;&lt;label&gt;Needs Action&lt;/label&gt;&lt;/status&gt;&lt;module&gt;&lt;id&gt;_pc_ls_laqs053&lt;/id&gt;&lt;title&gt;Ethical Characteristics&lt;/title&gt;&lt;type&gt;&lt;code&gt;onlineModule&lt;/code&gt;&lt;label&gt;Online&lt;/label&gt;&lt;/type&gt;&lt;description&gt;Ethical Characteristics&amp;#13;
        ///&lt;/description&gt;&lt;/module&gt;&lt;url&gt;/preview/servlet/ekp?CID=_pc_ls_laqs053&amp;amp;TX=FORMAT1&amp;amp;BACKTOCATALOG=Y&amp;amp;DECORATEPAGE=N&lt;/url&gt;&lt;optional&gt;false&lt;/optional&gt;&lt;priority&gt;&lt;code&gt;high&lt;/code&gt;&lt;label&gt;High&lt;/label&gt;&lt;/pr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string learningPath {
            get {
                return ResourceManager.GetString("learningPath", resourceCulture);
            }
        }
    }
}
